### ISSUE TITLE
suggestion: how to fire actionsheet from within a JQM listview

### ISSUE THREAD

**Issue by frequent** [hiroprotagonist/jquery.mobile.actionsheet#11]
I tried to put the actionsheet trigger into a JQM listview. Did not work as-is.

I got it to work by doing the following:
- also check for parents(li) before applying button markup to not get a list-item-button
- replace data-role="actionsheet" with data-trigger="actionsheet" to preserve data-role (for buttons or other)
- add an id to the trigger link and same class to the corresponding action sheet and replace next(div) with a query for class with id of trigger
- this way you can put the action sheet div anywhere you want, as placing it right after a list elements link will also break the script

If you want I can make a commit of the modified version. Maybe something you can use.

Sonst ein super Plugin!

**Comment by hiroprotagonist** [comment]
Hey Sven,
its already possible to associate toggle and action sheet via html-id's. The action sheet must not follow its toggle, its optional. See the example index.html or the readme.
Anyway if you have something useful i suggest creating a gist. What do you think?

**Comment by frequent** [comment]
I put the changes here:

git://gist.github.com/1209324.git

It's not perfect yet, but working already.
