### ISSUE TITLE
Doesn't work with Webkit

### ISSUE THREAD

**Issue by dave7oaks** [hiroprotagonist/jquery.mobile.actionsheet#14]
This plugin is exactly what I was looking for however unfortunately it doesn't seem to work with Webkit browsers (tested on iPhone and Chrome). Any ideas why or plans to fix?

**Comment by hiroprotagonist** [comment]
I've tested the plugin on two different android tablets on an andro phone, iphone 3GS and 4 as also on ipad 1 sucessfully.
I need more info on your test case.

**Comment by dave7oaks** [comment]
Hmmm strange - I have tried it on my iPhone 3GS (running iOS 5) and on Chrome (on my mac). In both cases I get a grey box appearing but there is no content.

**Comment by dave7oaks** [comment]
If you send me your email address I can drop you some screen shots if it will help.

**Comment by hiroprotagonist** [comment]
Can you please check if the example.html is working. Just clone the repository and point your browser to example.html.

**Comment by hiroprotagonist** [comment]
Oh damn it, you're right.
The plugin is not working as it should with jqm 1.0 final.

**Comment by dave7oaks** [comment]
I am actually using the last rc (still havent switched over). I havent had a chance to look at it properly but I thought it might have something to do with having multiple div's with data-role="content" (which I have in that particular page) because that grey block on webkit browsers corresponds with one of these divs. Anyway let me know if I can help out with any testing.

**Comment by hiroprotagonist** [comment]
Can you send me your page please?
One question: Why are you using my plugin instead of the jqm built in dialog?
