### ISSUE TITLE
Turn of Background  and Content

### ISSUE THREAD

**Issue by emitte** [hiroprotagonist/jquery.mobile.actionsheet#17]
I think that the turn of Background and Content is reverse.

Background are coming above Content. 

I am developing iPhone App using jQuery Mobile 1.0 Final & PhoneGap.

**Comment by hiroprotagonist** [comment]
Dont think so. z-index of the wallpaper is 19. z-index of content is 20. This should be ok.
The z-index of a fixed footer is 1000. To overlay a this increase zindexs of wallpaper and content.
