### ISSUE TITLE
Multiple dialog on one page

### ISSUE THREAD

**Issue by larousse** [hiroprotagonist/jquery.mobile.actionsheet#20]
This is working beautifully for me.

Here is where I can use some help if possible.

I have a navbar with 4 buttons in the footer, 2 of them launch a dialog but I would like to have only one open at a time.Which means that one of the overlays is active (displayed), I would like it to hide when the other overlay is activated by clicking on the a  data-role="actionsheet". I have tried a few things without success. Thanks!

```
    a href="#home">Home
    a href="#groupdata">Groups
    a data-role="actionsheet" data-sheet='map_filter_overlay' id="filter-a">Map Filter
    a data-role="actionsheet" data-sheet='holeselector_overlay' >Go to Hole
```

**Comment by hiroprotagonist** [comment]
Hey larousse
I've extend the sample page. Take a look at the diff of this commit. This will help you.
https://github.com/hiroprotagonist/jquery.mobile.actionsheet/commit/2028dd45ed26c22fe9b17555a36b0104c234ad19

Cheers
Stefan

**Comment by larousse** [comment]
Awesome! thanks!!!!
