### ISSUE TITLE
How to call in JS?

### ISSUE THREAD

**Issue by justechn** [hiroprotagonist/jquery.mobile.actionsheet#24]
I am building my page with ajax and it is not linking the actionsheet to the link. I assume this is because your code is running before my page is done building. So I need to know how to call this code after I am done building my page with ajax?

**Comment by hiroprotagonist** [comment]
$('a#your_toggle_id').actionsheet();

**Comment by justechn** [comment]
Thank you very much. I ended up using code like this  

$( ":jqmData(role='page') :jqmData(role='actionsheet')" ).each(function() {
    $(this).actionsheet();
});
