### ISSUE TITLE
Using close causes an unbind error

### ISSUE THREAD

**Issue by justechn** [hiroprotagonist/jquery.mobile.actionsheet#26]
I see in your example that you can include a cancel button in the actionsheet, but when I try I get an unbind error.

Here is my actionsheet (still in development)
```<a href="shopping_item.php" data-role="button" data-theme="c" onclick="$('a#sheet_editShoppingItem').actionsheet('close');">Edit</a>
     <a href="#" data-role="button" data-theme="c">Delete</a>
     <a href="#" data-role="button" data-theme="c">Copy</a>
     <a href="#" data-role="button" data-theme="c">Move</a>
     <a href="#" data-role="button" data-theme="c" data-rel="close">Cancel</a>

```

here is the error
jquery.mobile.actionsheet.js:72 Uncaught TypeError: Cannot call method 'unbind' of undefined

Do you have any ideas?
```

**Comment by justechn** [comment]
The problem seems to occur when you have more than one link pointing to the same actionsheet.

For example I have a list of items and when I click on one item in the list I want it to open an actionsheet which has a bunch of options, like edit, delete, copy, move, and cancel. So to make things cleaner I have just one actionsheet and every item in the list points to the same one.

**Comment by hiroprotagonist** [comment]
Actionsheet is a tradeoff between "easy to use" and functionality.
I think a pure JS approach will work better for your use case. Take a look at this one:
https://github.com/jtsage/jquery-mobile-simpledialog
