### ISSUE TITLE
Clicking in footer does not close action sheet

### ISSUE THREAD

**Issue by mdeckert** [hiroprotagonist/jquery.mobile.actionsheet#29]
I have 3 different action sheets in my footer.  If I click one it works just fine, except that the footer is not part of the "wallpaper" that closes the actionsheet.  This leads to my problem, since if I have one action sheet open, I can still click a different actionsheet in the footer and then this one pops up over the existing one.

I would either like to have the wallpaper extend into the footer (so I can't select a new sheet until I cancel the existing one) or learn how to close the open sheet before opening the new one.

**Comment by hiroprotagonist** [comment]
hey mdeckert
you have to close/toggle the widgets manually. but no problem thats quite easy. i've made an example how that works.
take a quick look at the footer of the following example. there are two actionsheet. when opening the first it will close the
second and vice versa. this should help you. 
https://github.com/hiroprotagonist/jquery.mobile.actionsheet/blob/master/examples/singlepage.html

cheers
