### ISSUE TITLE
To force close method without animate '...animateOut'

### ISSUE THREAD

**Issue by gcsis** [hiroprotagonist/jquery.mobile.actionsheet#31]
It is sometimes necessary to not be performed close transitions, for example to avoid flicker when deriving to other elements with animate.
For this, I propose change within the close method (see internal 'if'):

```
if( $.support.cssTransitions ) {       ...       }
```

new 'if' conditions (taking advantage of event param):

```
if( $.support.cssTransitions && event!==false ) {       ...      }
```

 so you can call to close without transition : 

```
$('#sheet').actionsheet('close',false);
```

**Comment by hiroprotagonist** [comment]
Hmmm. Thanks for the idea but i dont like it.
