### ISSUE TITLE
actionsheet not looking like a button

### ISSUE THREAD

**Issue by chantalplx** [hiroprotagonist/jquery.mobile.actionsheet#33]
This is a really nice plugin but I am wondering if it is possible to change the look of the button. To tell you the truth, I don't want the text that calls the popup to look like a button. I want it to be plain text. I looked at the css sheet but cannot find where to change it. Is it in the js file? If it is, how can I change that?

**Comment by hiroprotagonist** [comment]
hi its quite a while when i had the last look at this plugin and jqm at all. take a look at issue #25 There is a solution if the opener is part of the div[data-role=content] If your opener is part the head just a span-tag instead of an a-tag.
