### ISSUE TITLE
Links with rel='external' doesnt work on Android ...

### ISSUE THREAD

**Issue by dmarko484** [hiroprotagonist/jquery.mobile.actionsheet#8]
Thank you for this marvelous JQ Mobile plugin .... I'm trying to use it but I found that when I have a link with rel='external' the link doesnt work on Android phone. Its working fine in Chrome for example but not on my mobile phone.  Without rel attribute it works fine ... is this something known or how to make this work properly for this case?

Thank you !!!
David

**Comment by hiroprotagonist** [comment]
Strange thing. The plugin does not modify the control elements
Anchors,Inputs... whatever. I got an android phone in my office. I will
check that tomorrow.

Cheers
Stefan

**Comment by hiroprotagonist** [comment]
Hi David
Youre right its a bug. I'll fix it.

**Comment by dmarko484** [comment]
Thanks for such support ...

David

2011/8/17 hiroprotagonist <
reply@reply.github.com>

**Comment by dmarko484** [comment]
Hello, any news on this bug?

**Comment by hiroprotagonist** [comment]
Was on holidays. I dont no why external links wont handle the tap on android when the links are part of an actionsheet. The only thing i can offer for now is this hacky workaround:
$('a.xxx').bind( 'tap', function(){ window.location = this.href; } );

**Comment by nbussman** [comment]
still the same problem with android standart browser. using android 2.2. Can anyone help me, need it for a my bachlor work :) thx

**Comment by nbussman** [comment]
it's allright. just make it width  $('a.xxx').bind( 'tap', function(){ window.location = this.href; } ); Works for me:) thanks

**Comment by hiroprotagonist** [comment]
Bueno. 

Self do, self have!
