### ISSUE TITLE
Feature request "android like action sheet"

### ISSUE THREAD

**Issue by nbenitez** [hiroprotagonist/jquery.mobile.actionsheet#9]
Hi, thank you for creating jquery.mobile.actionsheet it's definitly a very useful plugin that I'm planning to introduce in an open-source jquerymobile game I'm developing for android.. but, it seems to me that is too ios oriented, which is good, but I'll appreciate some config options to turn it more like android action sheet, if you ask me how android action sheet looks like I would say pretty much like this:

http://dev.sencha.com/deploy/touch/examples/kitchensink/     (Go to User Inferface -> Overlays -> Action Sheet)

so the two only things I'm missing are:
1) the popup be positioned at footer of page, with the background taking all the width of the screen.
2) A way to programatically open the action-sheet, without any need for the <a link, because I want the user to open the sheet when he presses the settings button on android, and so no user interface is needed to open it.

I think 1) could be activated in some "android mode" setting..

I would like to know if you think these features are interesting and consider to implement them or accept patches about them.. 

Thank you!

**Comment by hiroprotagonist** [comment]
Actually the widget gets positioned by js-script. A much better solution would be 100% CSS positioning but not implemented yet. 
Of course you still can hack your needs into the js file.
You can programmatically instrument an actionsheet:
jQuery('#x').actionsheet('open');
as well as: jQuery('#x').actionsheet('close')

The toggle to open is concept. But feel free to write an alternative version.
